export{default as Navbar} from './navbar/navbar'
export {default as Footer} from './footer/footer'
export {default as Hero} from './hero/Hero'
export{default as Siderbar} from './sidebar/Sidebar'
export{default as Content} from './content/Content'
